[service]
name = "mcpo"
startCommand = "/bin/sh -c 'exec uvx mcpo --port 8000 --api-key ${MCPO_API_KEY} --name n8n_tool --server-type ${SERVER_TYPE} -- https://n8n-railway-custom-production-5457.up.railway.app/mcp/starter'"

[build]
builder = "dockerfile"

[dockerfile]
path = "./Dockerfile"

[ports]
http = 8000

[[envVars]]
key = "MCPO_API_KEY"
value = "your-secret-key"

[[envVars]]
key = "SERVER_TYPE"
value = "streamable-http"
